export const WORD_POS      = [0,    2.0,  0  ] as [number,number,number];
export const TITO_REST     = [5.0,  0,    0.5] as [number,number,number];
export const TITO_HIT      = [0.2,  2.0,  0.5] as [number,number,number];
export const TITO_BACK     = [2.8,  0,    0.5] as [number,number,number];
export const LIA_REST      = [-5.0, 0,    0.5] as [number,number,number];
export const LIA_BTN       = [-3.6, 0,    0.8] as [number,number,number];
export const CLAW_TOP_Y    = 5.0;
export const CABLE_MAX_LEN = 2.9;
export const CABLE_MIN_LEN = 0.45;